// stubs/app/vue/resources/vue/app/site/sections/legacy/section/FaqSection.vue
<template>

    <section class="site-section site-section-alt">

        <div class="site-container site-narrow">

            <div v-if="filled(title) || filled(subtitle)" class="site-heading-center">
                <h2 v-if="filled(title)" class="site-title">{{ title }}</h2>
                <p v-if="filled(subtitle)" class="site-lead">{{ subtitle }}</p>
            </div>

            <!-- <details> ya es un acordeón accesible: teclado, estado abierto y
                 lectura en voz alta, sin una línea de JavaScript. -->
            <div v-if="entries.length" class="site-faq">
                <details v-for="(entry, index) in entries" :key="index" class="site-faq-item">
                    <summary class="site-faq-question">
                        <span>{{ entry.question }}</span>
                        <IconComponent name="down" :size="12" custom-class="site-faq-chevron" />
                    </summary>
                    <p class="site-faq-answer">{{ entry.answer }}</p>
                </details>
            </div>

        </div>

    </section>

</template>

<script setup>

    import { computed } from 'vue'
    import { IconComponent } from 'innoboxrr-form-elements'
    import { asArray, asObject, asText, filled } from '../../props.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['title', 'subtitle', 'items'])

    const entries = computed(() => asArray(props.items)
        .map(asObject)
        .filter((item) => filled(item.question))
        .map((item) => ({ question: asText(item.question), answer: asText(item.answer) })))

</script>

// stubs/app/react/resources/react/app/site/sections/legacy/section/FaqSection.jsx
import { asArray, asText, SectionHeader } from '../../shared.jsx'

/**
 * @param {{ props: { title?: string, subtitle?: string, items?: Array<{question: string, answer: string}> } }} props
 */
export default function FaqSection({ props = {} }) {
    const items = asArray(props.items).filter((item) => asText(item?.question) !== '')

    return (
        <section className="site-section">
            <div className="site-container">
                <SectionHeader title={props.title} subtitle={props.subtitle} />

                {items.length > 0 ? (
                    <dl className="site-faq">
                        {items.map((item, index) => (
                            <div key={`${index}-${item.question}`} className="site-faq-item">
                                <dt>{asText(item.question)}</dt>
                                <dd>{asText(item.answer)}</dd>
                            </div>
                        ))}
                    </dl>
                ) : null}
            </div>
        </section>
    )
}
