// stubs/app/vue/resources/vue/app/site/sections/legacy/section/JoinSection.vue
<template>

    <section class="site-section">

        <div class="site-container">

            <div class="site-join" :data-media="picture ? 'true' : 'false'">

                <img v-if="picture" :src="picture" alt="" class="site-media site-join-image" loading="lazy">

                <div>
                    <h2 v-if="filled(title)" class="site-title">{{ title }}</h2>
                    <p v-if="filled(subtitle)" class="site-lead">{{ subtitle }}</p>

                    <ul v-if="items.length" class="site-check-list site-join-features">
                        <li v-for="(feature, index) in items" :key="index">
                            <IconComponent name="success" :size="16" custom-class="site-check-icon" />
                            <span>{{ feature }}</span>
                        </li>
                    </ul>

                    <div v-if="filled(button_text)" class="site-actions">
                        <SiteLink :to="asText(button_link)" class="fe-button site-button-lg">
                            {{ button_text }} <span aria-hidden="true">→</span>
                        </SiteLink>
                    </div>
                </div>

            </div>

        </div>

    </section>

</template>

<script setup>

    import { computed } from 'vue'
    import { IconComponent } from 'innoboxrr-form-elements'
    import SiteLink from '../../../SiteLink.vue'
    import { asText, filled, imageUrl, textList } from '../../props.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['title', 'subtitle', 'image', 'features', 'button_text', 'button_link'])

    const picture = computed(() => imageUrl(props.image))

    const items = computed(() => textList(props.features))

</script>

// stubs/app/react/resources/react/app/site/sections/legacy/section/JoinSection.jsx
import { asText, Checklist, OptionalImage, SmartLink } from '../../shared.jsx'

/**
 * @param {{ props: { title?: string, subtitle?: string, image?: string, features?: string[], button_text?: string, button_link?: string } }} props
 */
export default function JoinSection({ props = {} }) {
    const title = asText(props.title)
    const subtitle = asText(props.subtitle)
    const button = asText(props.button_text)
    const hasImage = asText(props.image) !== ''

    return (
        <section className="site-section">
            <div className="site-container">
                <div className="site-join-card" data-media={hasImage ? 'true' : 'false'}>
                    <OptionalImage src={props.image} className="site-join-image" />

                    <div>
                        {title !== '' ? <h2 className="site-heading">{title}</h2> : null}
                        {subtitle !== '' ? <p className="site-lead">{subtitle}</p> : null}

                        <Checklist items={props.features} columns={2} />

                        {button !== '' ? (
                            <div className="site-actions">
                                <SmartLink href={props.button_link} className="fe-button site-button-lg">
                                    {button} <span aria-hidden="true">→</span>
                                </SmartLink>
                            </div>
                        ) : null}
                    </div>
                </div>
            </div>
        </section>
    )
}
