// stubs/app/vue/resources/vue/app/site/sections/legacy/section/MissionSection.vue
<template>

    <section class="site-section">

        <div class="site-container site-split" :data-media="pictures.length ? 'true' : 'false'">

            <div>
                <h2 v-if="filled(title)" class="site-title">{{ title }}</h2>
                <p v-if="filled(subtitle)" class="site-subtitle">{{ subtitle }}</p>
                <p v-if="filled(message)" class="site-text">{{ message }}</p>
                <div v-if="filled(button_text)" class="site-actions">
                    <SiteLink :to="asText(button_link)" class="fe-button site-button-lg">
                        {{ button_text }} <span aria-hidden="true">→</span>
                    </SiteLink>
                </div>
            </div>

            <div v-if="pictures.length" class="site-mosaic" :data-count="pictures.length">
                <img v-for="(src, index) in pictures" :key="index" :src="src" alt="" class="site-media" loading="lazy">
            </div>

        </div>

    </section>

</template>

<script setup>

    import { computed } from 'vue'
    import SiteLink from '../../../SiteLink.vue'
    import { asText, filled, imageList } from '../../props.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['title', 'subtitle', 'message', 'button_text', 'button_link', 'images'])

    const pictures = computed(() => imageList(props.images, 4))

</script>

// stubs/app/react/resources/react/app/site/sections/legacy/section/MissionSection.jsx
import { asArray, asText, OptionalImage, SmartLink } from '../../shared.jsx'

/**
 * @param {{ props: { title?: string, subtitle?: string, message?: string, button_text?: string, button_link?: string, images?: string[] } }} props
 */
export default function MissionSection({ props = {} }) {
    const images = asArray(props.images).map(asText).filter((src) => src !== '').slice(0, 4)
    const title = asText(props.title)
    const subtitle = asText(props.subtitle)
    const message = asText(props.message)
    const button = asText(props.button_text)

    return (
        <section className="site-section site-section-alt">
            <div className="site-container site-split" data-media={images.length > 0 ? 'true' : 'false'}>
                <div className="site-mission-copy">
                    {title !== '' ? <h2 className="site-heading">{title}</h2> : null}
                    {subtitle !== '' ? <p className="site-lead">{subtitle}</p> : null}
                    {message !== '' ? <p className="site-body">{message}</p> : null}

                    {button !== '' ? (
                        <div className="site-actions">
                            <SmartLink href={props.button_link} className="fe-button site-button-lg">
                                {button} <span aria-hidden="true">→</span>
                            </SmartLink>
                        </div>
                    ) : null}
                </div>

                {images.length > 0 ? (
                    <div className="site-mosaic" data-count={images.length}>
                        {images.map((src, index) => <OptionalImage key={`${index}-${src}`} src={src} className="site-mosaic-img" />)}
                    </div>
                ) : null}
            </div>
        </section>
    )
}
