// stubs/app/vue/resources/vue/app/site/sections/legacy/cookie-consent/CookieConsentOne.vue
<template>

    <div v-if="! decision" class="site-cookie" role="region" :aria-label="t('Cookie consent')">

        <p class="site-cookie-text">
            {{ text }}
            <SiteLink v-if="filled(policy_link)" :to="asText(policy_link)" class="site-cookie-link">{{ t('Learn more') }}</SiteLink>
        </p>

        <div class="site-cookie-actions">
            <button type="button" class="fe-button fe-button-sm" @click="decide('accepted')">{{ acceptText }}</button>
            <button type="button" class="fe-button-secondary fe-button-sm" @click="decide('rejected')">{{ rejectText }}</button>
        </div>

    </div>

</template>

<script setup>

    import { computed, ref } from 'vue'
    import t from 'innoboxrr-i18n'
    import SiteLink from '../../../SiteLink.vue'
    import { readConsent, writeConsent } from '../../../cookies.js'
    import { asText, filled } from '../../props.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['message', 'accept_text', 'reject_text', 'policy_link'])

    // Una decisión, aceptar o rechazar, se recuerda igual: el aviso no vuelve.
    const decision = ref(readConsent())

    const text = computed(() => (filled(props.message)
        ? asText(props.message)
        : t('We use cookies to make the site work and to remember your preferences.')))

    const acceptText = computed(() => (filled(props.accept_text) ? asText(props.accept_text) : t('Accept')))

    const rejectText = computed(() => (filled(props.reject_text) ? asText(props.reject_text) : t('Reject')))

    const decide = (value) => {
        writeConsent(value)
        decision.value = value
    }

</script>

// stubs/app/react/resources/react/app/site/sections/legacy/cookie-consent/CookieConsentOne.jsx
import { useState } from 'react'
import t from 'innoboxrr-i18n'

import { asText, SmartLink } from '../../shared.jsx'

export const CONSENT_COOKIE = 'cookie_consent'

export function readConsent(cookies = document.cookie) {
    const value = cookies
        .split(';')
        .map((part) => part.trim())
        .find((part) => part.startsWith(`${CONSENT_COOKIE}=`))
        ?.slice(CONSENT_COOKIE.length + 1)

    return value === 'accepted' || value === 'rejected' ? value : null
}

function writeConsent(value) {
    document.cookie = `${CONSENT_COOKIE}=${value}; max-age=${60 * 60 * 24 * 365}; path=/; SameSite=Lax`
}

/**
 * Guarda la decisión en la cookie `cookie_consent` y no vuelve a salir.
 *
 * @param {{ props: { message?: string, accept_text?: string, reject_text?: string, policy_link?: string } }} props
 */
export default function CookieConsentOne({ props = {} }) {
    const [decided, setDecided] = useState(() => readConsent() !== null)

    if (decided) {
        return null
    }

    const decide = (value) => {
        writeConsent(value)
        setDecided(true)
    }

    return (
        <div className="site-cookie" role="region" aria-label={t('Cookie consent')}>
            <p>
                {asText(props.message) || t('We use cookies to make the site work and to remember your preferences.')}

                {asText(props.policy_link) !== '' ? (
                    <>
                        {' '}
                        <SmartLink href={props.policy_link}>{t('Learn more')}</SmartLink>
                    </>
                ) : null}
            </p>

            <div className="site-actions">
                <button type="button" className="fe-button" onClick={() => decide('accepted')}>
                    {asText(props.accept_text) || t('Accept')}
                </button>

                <button type="button" className="fe-button-secondary" onClick={() => decide('rejected')}>
                    {asText(props.reject_text) || t('Reject')}
                </button>
            </div>
        </div>
    )
}
