// stubs/app/react/resources/react/app/site/sections/legacy/header/HeaderOne.jsx
import { useEffect, useId, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import t from 'innoboxrr-i18n'
import { IconComponent } from 'innoboxrr-react-form-elements'

import ThemeToggle from '../../../../components/ThemeToggle.jsx'
import { useAuthStore } from '../../../../stores/auth.js'
import { useSiteName } from '../../../../stores/options.js'
import { asArray, asText, Brand, SmartLink, SocialLinks } from '../../shared.jsx'

/**
 * @param {{ props: { logo?: string, nav?: Array<{label: string, link: string}>, facebook?: string, twitter?: string, instagram?: string, youtube?: string, whatsapp?: string, linkedin?: string, tiktok?: string } }} props
 */
export default function HeaderOne({ props = {} }) {
    const authenticated = useAuthStore((state) => state.authenticated)
    const siteName = useSiteName()
    const location = useLocation()
    const navId = useId()
    const [open, setOpen] = useState(false)

    const nav = asArray(props.nav).filter((item) => asText(item?.label) !== '')

    useEffect(() => setOpen(false), [location.pathname])

    return (
        <header className="site-header">
            <div className="site-container site-header-bar">
                <Brand logo={props.logo} name={siteName} />

                <button
                    type="button"
                    className="fe-icon-button site-nav-toggle"
                    aria-expanded={open}
                    aria-controls={navId}
                    aria-label={open ? t('Close menu') : t('Open menu')}
                    onClick={() => setOpen((value) => ! value)}>
                    <IconComponent name={open ? 'close' : 'menu'} size={18} />
                </button>

                <nav id={navId} className="site-nav" data-open={open ? 'true' : 'false'} aria-label={t('Site')}>
                    {nav.length > 0 ? (
                        <ul className="site-nav-list">
                            {nav.map((item, index) => (
                                <li key={`${index}-${item.label}`}>
                                    <SmartLink href={item.link} className="site-nav-link">{asText(item.label)}</SmartLink>
                                </li>
                            ))}
                        </ul>
                    ) : null}

                    <div className="site-nav-actions">
                        <SocialLinks links={props} />

                        <ThemeToggle />

                        <Link to={authenticated ? '/admin' : '/auth/login'} className="fe-button">
                            {authenticated ? t('Administrator') : t('Sign in')}
                        </Link>
                    </div>
                </nav>
            </div>
        </header>
    )
}

// stubs/app/vue/resources/vue/app/site/sections/legacy/header/HeaderOne.vue
<template>

    <header class="site-header">

        <div class="site-container site-header-bar">

            <RouterLink :to="{ name: 'site.home' }" class="site-brand">
                <img v-if="logoUrl" :src="logoUrl" :alt="siteName" class="site-brand-logo">
                <span v-else class="site-brand-name">{{ siteName }}</span>
            </RouterLink>

            <button
                type="button"
                class="fe-icon-button site-header-toggle"
                :aria-expanded="open ? 'true' : 'false'"
                :aria-controls="panelId"
                :aria-label="open ? t('Close menu') : t('Open menu')"
                @click="open = ! open">
                <IconComponent :name="open ? 'close' : 'menu'" />
            </button>

            <div :id="panelId" class="site-header-panel" :data-open="open ? 'true' : 'false'">

                <nav v-if="links.length" :aria-label="t('Main navigation')">
                    <ul class="site-header-links">
                        <li v-for="(item, index) in links" :key="index">
                            <SiteLink :to="item.link" class="site-header-link" @click="open = false">{{ item.label }}</SiteLink>
                        </li>
                    </ul>
                </nav>

                <ul v-if="socials.length" class="site-social" :aria-label="t('Social networks')">
                    <li v-for="item in socials" :key="item.id">
                        <a :href="item.href" class="fe-icon-button" target="_blank" rel="noopener noreferrer" :aria-label="item.label">
                            <IconComponent :name="item.icon" :size="16" />
                        </a>
                    </li>
                </ul>

                <RouterLink
                    v-if="auth.authenticated"
                    :to="{ name: 'admin.dashboard' }"
                    class="fe-button fe-button-sm site-header-cta">{{ t('Administrator') }}</RouterLink>

                <RouterLink
                    v-else
                    :to="{ name: 'auth.login' }"
                    class="fe-button fe-button-sm site-header-cta">{{ t('Sign in') }}</RouterLink>

            </div>

        </div>

    </header>

</template>

<script setup>

    import { computed, ref, useId } from 'vue'
    import { RouterLink } from 'vue-router'
    import t from 'innoboxrr-i18n'
    import { IconComponent } from 'innoboxrr-form-elements'
    import { useAuthStore } from '@app/stores/auth.js'
    import { useOptionsStore } from '@app/stores/options.js'
    import SiteLink from '../../../SiteLink.vue'
    import { asArray, asObject, asText, filled, imageUrl } from '../../props.js'
    import { socialLinks } from '../../social.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['logo', 'nav', 'facebook', 'twitter', 'instagram', 'youtube', 'whatsapp', 'linkedin', 'tiktok'])

    const auth = useAuthStore()
    const options = useOptionsStore()

    const open = ref(false)
    const panelId = useId()

    const siteName = computed(() => asText(options.option('site_name', '')))

    const logoUrl = computed(() => imageUrl(props.logo))

    const links = computed(() => asArray(props.nav)
        .map(asObject)
        .filter((item) => filled(item.label))
        .map((item) => ({ label: asText(item.label), link: asText(item.link) })))

    const socials = computed(() => socialLinks(props))

</script>
