// stubs/app/react/resources/react/app/auth/LoginView.jsx
import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import t from 'innoboxrr-i18n'
import { notifyError } from 'innoboxrr-form-core'
import { TextInputComponent } from 'innoboxrr-react-form-elements'

import { errorMessage } from '../forms/errors.js'
import useValidator from '../forms/useValidator.js'
import { safeRedirect } from '../router/guards.js'
import { useAuthStore } from '../stores/auth.js'

export default function LoginView() {
    const login = useAuthStore((state) => state.login)
    const navigate = useNavigate()
    const [params] = useSearchParams()
    const { form, showServerErrors } = useValidator()

    const [values, setValues] = useState({ email: '', password: '', remember: false })
    const [busy, setBusy] = useState(false)

    const field = (name) => (value) => setValues((current) => ({ ...current, [name]: value }))

    const submit = async (event) => {
        event.preventDefault()
        setBusy(true)

        try {
            await login(values)

            navigate(safeRedirect(params.get('redirect')), { replace: true })
        } catch (error) {
            if (! showServerErrors(error)) {
                notifyError(errorMessage(error))
            }
        } finally {
            setBusy(false)
        }
    }

    return (
        <>
            <h1 className="app-auth-title">{t('Log in')}</h1>
            <p className="app-auth-lead">{t('Enter your email and password to continue.')}</p>

            <form ref={form} onSubmit={submit} noValidate>
                <TextInputComponent
                    label={t('Email')}
                    name="email"
                    type="email"
                    autoComplete="email"
                    validators="required email"
                    value={values.email}
                    onChange={field('email')} />

                <TextInputComponent
                    label={t('Password')}
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    validators="required"
                    showPasswordLabel={t('Show password')}
                    hidePasswordLabel={t('Hide password')}
                    value={values.password}
                    onChange={field('password')} />

                <label className="app-check">
                    <input
                        type="checkbox"
                        className="fe-checkbox"
                        name="remember"
                        checked={values.remember}
                        onChange={(event) => field('remember')(event.target.checked)} />
                    {t('Remember me')}
                </label>

                <button type="submit" className="fe-button app-block" disabled={busy}>
                    {busy ? t('Logging in…') : t('Log in')}
                </button>
            </form>

            <p className="app-auth-links">
                <Link to="/auth/forgot-password">{t('Forgot your password?')}</Link>
                <Link to="/auth/register">{t('Create an account')}</Link>
            </p>
        </>
    )
}

// stubs/app/vue/resources/vue/app/auth/LoginView.vue
<template>

    <form ref="form" novalidate @submit.prevent="handleSubmit">

        <h1 class="auth-title">{{ t('Sign in') }}</h1>
        <p class="auth-intro">{{ t('Welcome back. Enter your email and your password.') }}</p>

        <p v-if="error" class="app-alert" role="alert">{{ error }}</p>

        <FormField
            v-model="email"
            name="email"
            type="email"
            :label="t('Email')"
            autocomplete="email"
            validators="required email"
            autofocus />

        <FormField
            v-model="password"
            name="password"
            type="password"
            :label="t('Password')"
            autocomplete="current-password"
            validators="required" />

        <div class="auth-row">
            <label class="app-check">
                <input v-model="remember" type="checkbox" name="remember" class="fe-checkbox">
                {{ t('Remember me') }}
            </label>
            <RouterLink :to="{ name: 'auth.forgot-password' }">{{ t('Forgot your password?') }}</RouterLink>
        </div>

        <button type="submit" class="fe-button auth-submit" :disabled="busy">
            {{ busy ? t('Signing in…') : t('Sign in') }}
        </button>

        <p class="auth-links">
            <span>{{ t("Don't have an account?") }}</span>
            <RouterLink :to="{ name: 'auth.register', query: route.query }">{{ t('Create account') }}</RouterLink>
        </p>

    </form>

</template>

<script setup>

    import { ref } from 'vue'
    import { RouterLink, useRoute, useRouter } from 'vue-router'
    import t from 'innoboxrr-i18n'
    import FormField from '@app/components/FormField.vue'
    import { useValidatedForm } from '@app/components/useValidatedForm.js'
    import { safeRedirect } from '@app/router/guards.js'
    import { useAuthStore } from '@app/stores/auth.js'

    const route = useRoute()
    const router = useRouter()
    const auth = useAuthStore()

    const email = ref('')
    const password = ref('')
    const remember = ref(false)

    const { form, busy, error, handleSubmit } = useValidatedForm(async ({ setError }) => {
        await auth.login({ email: email.value, password: password.value, remember: remember.value })

        // El login respondió bien pero la sesión no llegó a get-auth: la cookie
        // no se guarda, casi siempre por SANCTUM_STATEFUL_DOMAINS o SESSION_DOMAIN.
        if (! auth.authenticated) {
            setError(t('You signed in, but the session was not kept. Check the session and Sanctum domains.'))

            return
        }

        await router.replace(safeRedirect(route.query.redirect) ?? { name: 'admin.dashboard' })
    })

</script>
