// stubs/app/react/resources/react/app/site/sections/legacy/section/TestimonialsSection.jsx
import { useState } from 'react'

import { asArray, asObject, asText, SectionHeader } from '../../shared.jsx'

const initials = (name) => asText(name).split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0].toUpperCase()).join('')

/**
 * Un testimonio en la forma que pinta la sección, o null si no tiene texto.
 * `message` era el nombre de la clave en las aplicaciones antiguas.
 */
export function normalizeTestimonial(value, featured = false) {
    const item = asObject(value)
    const author = asObject(item.author)
    const body = asText(item.body ?? item.message)

    if (body.trim() === '') {
        return null
    }

    return {
        featured,
        body,
        name: asText(author.name),
        handle: asText(author.handle),
        image: asText(author.image).trim(),
    }
}

function Author({ entry }) {
    const [broken, setBroken] = useState(false)

    if (entry.name === '' && entry.handle === '') {
        return null
    }

    return (
        <figcaption className="site-author">
            {entry.image !== '' && ! broken
                ? <img className="site-author-avatar" src={entry.image} alt="" loading="lazy" onError={() => setBroken(true)} />
                : <span className="site-author-avatar" aria-hidden="true">{initials(entry.name)}</span>}

            <span>
                {entry.name !== '' ? <span className="site-author-name">{entry.name}</span> : null}
                {entry.handle !== '' ? <span className="site-author-handle">{entry.handle}</span> : null}
            </span>
        </figcaption>
    )
}

/**
 * @param {{ props: { title?: string, subtitle?: string, feature?: {body: string, author: {name: string, handle: string, image?: string}}, items?: Array<{body: string, author: {name: string, handle: string, image?: string}}> } }} props
 */
export default function TestimonialsSection({ props = {} }) {
    const featured = normalizeTestimonial(props.feature, true)
    const entries = asArray(props.items).map((item) => normalizeTestimonial(item)).filter(Boolean)
    const all = featured ? [featured, ...entries] : entries

    return (
        <section className="site-section site-section-alt">
            <div className="site-container">
                <SectionHeader title={props.title} subtitle={props.subtitle} />

                {all.length > 0 ? (
                    <div className="site-testimonials">
                        {all.map((entry, index) => (
                            <figure key={index} className={entry.featured ? 'site-quote site-quote-featured' : 'site-quote'}>
                                <blockquote>
                                    <p>“{entry.body}”</p>
                                </blockquote>

                                <Author entry={entry} />
                            </figure>
                        ))}
                    </div>
                ) : null}
            </div>
        </section>
    )
}

// stubs/app/vue/resources/vue/app/site/sections/legacy/section/TestimonialsSection.vue
<template>

    <section class="site-section">

        <div class="site-container">

            <div v-if="filled(title) || filled(subtitle)" class="site-heading-center">
                <h2 v-if="filled(title)" class="site-title">{{ title }}</h2>
                <p v-if="filled(subtitle)" class="site-lead">{{ subtitle }}</p>
            </div>

            <div v-if="featured || entries.length" class="site-testimonials">

                <figure
                    v-for="(entry, index) in all"
                    :key="index"
                    class="site-card site-testimonial"
                    :class="{ 'site-testimonial-featured': entry.featured }">

                    <blockquote class="site-testimonial-body">
                        <p>“{{ entry.body }}”</p>
                    </blockquote>

                    <figcaption v-if="entry.name || entry.handle" class="site-author">
                        <img v-if="entry.image" :src="entry.image" alt="" class="site-avatar" loading="lazy">
                        <span v-else class="site-avatar" aria-hidden="true">{{ initials(entry.name) }}</span>
                        <span>
                            <span class="site-author-name">{{ entry.name }}</span>
                            <span v-if="entry.handle" class="site-author-handle">{{ entry.handle }}</span>
                        </span>
                    </figcaption>

                </figure>

            </div>

        </div>

    </section>

</template>

<script setup>

    import { computed } from 'vue'
    import { asArray, asObject, asText, filled, imageUrl, initials } from '../../props.js'

    defineOptions({ inheritAttrs: false })

    const props = defineProps(['title', 'subtitle', 'feature', 'items'])

    const normalize = (value, featured = false) => {
        const item = asObject(value)
        const author = asObject(item.author)
        // `message` era el nombre de la clave en las aplicaciones antiguas.
        const body = asText(item.body ?? item.message)

        if (body.trim() === '') {
            return null
        }

        return {
            featured,
            body,
            name: asText(author.name),
            handle: asText(author.handle),
            image: imageUrl(author.image),
        }
    }

    const featured = computed(() => normalize(props.feature, true))

    const entries = computed(() => asArray(props.items).map((item) => normalize(item)).filter(Boolean))

    const all = computed(() => (featured.value ? [featured.value, ...entries.value] : entries.value))

</script>
