// stubs/app/vue/resources/vue/app/auth/ForgotPasswordView.vue
<template>

    <form ref="form" novalidate @submit.prevent="handleSubmit">

        <h1 class="auth-title">{{ t('Forgot your password?') }}</h1>
        <p class="auth-intro">{{ t('Write your email and we will send you a link to choose a new one.') }}</p>

        <p v-if="error" class="app-alert" role="alert">{{ error }}</p>
        <p v-if="sent" class="app-alert" data-variant="success" role="status">{{ sent }}</p>

        <FormField v-model="email" name="email" type="email" :label="t('Email')" autocomplete="email" validators="required email" autofocus />

        <button type="submit" class="fe-button auth-submit" :disabled="busy">
            {{ busy ? t('Sending…') : t('Send the link') }}
        </button>

        <p class="auth-links">
            <RouterLink :to="{ name: 'auth.login' }">{{ t('Back to sign in') }}</RouterLink>
        </p>

    </form>

</template>

<script setup>

    import { ref } from 'vue'
    import { RouterLink } from 'vue-router'
    import t from 'innoboxrr-i18n'
    import FormField from '@app/components/FormField.vue'
    import { useValidatedForm } from '@app/components/useValidatedForm.js'
    import { useAuthStore } from '@app/stores/auth.js'

    const auth = useAuthStore()

    const email = ref('')
    const sent = ref('')

    const { form, busy, error, handleSubmit } = useValidatedForm(async () => {
        sent.value = ''

        // laravel-auth responde lo mismo exista o no la cuenta.
        const data = await auth.forgotPassword({ email: email.value })

        sent.value = data?.message ?? t('If the address is registered, we have emailed you a link.')
    })

</script>

// stubs/app/react/resources/react/app/auth/ForgotPasswordView.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import t from 'innoboxrr-i18n'
import { notifyError } from 'innoboxrr-form-core'
import { TextInputComponent } from 'innoboxrr-react-form-elements'

import { errorMessage } from '../forms/errors.js'
import useValidator from '../forms/useValidator.js'
import { useAuthStore } from '../stores/auth.js'

export default function ForgotPasswordView() {
    const forgotPassword = useAuthStore((state) => state.forgotPassword)
    const { form, showServerErrors } = useValidator()

    const [email, setEmail] = useState('')
    const [status, setStatus] = useState(null)
    const [busy, setBusy] = useState(false)

    const submit = async (event) => {
        event.preventDefault()
        setBusy(true)

        try {
            const data = await forgotPassword({ email })

            // laravel-auth responde lo mismo exista o no la cuenta.
            setStatus(data?.message ?? t('If the address is registered, we have emailed a password reset link.'))
        } catch (error) {
            if (! showServerErrors(error)) {
                notifyError(errorMessage(error))
            }
        } finally {
            setBusy(false)
        }
    }

    return (
        <>
            <h1 className="app-auth-title">{t('Forgot your password?')}</h1>
            <p className="app-auth-lead">{t('Enter your email and we will send you a link to choose a new one.')}</p>

            {status ? <p className="app-status" role="status">{status}</p> : null}

            <form ref={form} onSubmit={submit} noValidate>
                <TextInputComponent label={t('Email')} name="email" type="email" autoComplete="email" validators="required email" value={email} onChange={setEmail} />

                <button type="submit" className="fe-button app-block" disabled={busy}>
                    {busy ? t('Sending…') : t('Send the link')}
                </button>
            </form>

            <p className="app-auth-links">
                <Link to="/auth/login">{t('Back to log in')}</Link>
            </p>
        </>
    )
}
