// stubs/app/react/resources/react/app/site/SitePage.jsx
import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import t from 'innoboxrr-i18n'

import { readPath, useOptionsStore, useSiteName } from '../stores/options.js'
import ThemeManager from './ThemeManager.jsx'

import '../styles/site.css'

/**
 * Una página del sitio, pintada desde la opción `theme`.
 */
export default function SitePage({ page }) {
    const values = useOptionsStore((state) => state.values)
    const siteName = useSiteName()

    const data = readPath(values, `theme.${page}`, null)
    const exists = data !== null && typeof data === 'object' && ! Array.isArray(data)
    const title = exists && typeof data.title === 'string' ? data.title : ''

    useEffect(() => {
        document.title = title !== '' ? `${title} · ${siteName}` : siteName
    }, [title, siteName])

    if (! exists) {
        return (
            <main className="site site-empty">
                <h1 className="site-heading">{t('This page has no content yet')}</h1>

                <p className="site-lead">{t('An administrator can add it from the site editor.')}</p>

                <div className="site-actions">
                    <Link to="/" className="fe-button site-button-lg">{t('Go to the home page')}</Link>
                </div>
            </main>
        )
    }

    return (
        <div className="site">
            <ThemeManager sections={data.sections} />
        </div>
    )
}

// stubs/app/vue/resources/vue/app/site/SitePage.vue
<template>

    <ThemeManager v-if="page" :page="page" />

    <main v-else class="site site-empty">
        <div class="site-container site-narrow">
            <h1 class="site-title">{{ t('This page has no content yet') }}</h1>
            <p class="site-lead">{{ t('An administrator can add it from the site editor.') }}</p>
            <div class="site-actions">
                <RouterLink :to="{ name: 'site.home' }" class="fe-button site-button-lg">{{ t('Go to the home page') }}</RouterLink>
            </div>
        </div>
    </main>

</template>

<script setup>

    import { computed } from 'vue'
    import { RouterLink, useRoute } from 'vue-router'
    import t from 'innoboxrr-i18n'
    import { useOptionsStore } from '@app/stores/options.js'
    import ThemeManager from './ThemeManager.vue'

    const route = useRoute()
    const options = useOptionsStore()

    const page = computed(() => {
        const value = options.option(`theme.${route.meta.page}`)

        return value && typeof value === 'object' && ! Array.isArray(value) ? value : null
    })

</script>
